# Test environment is just running "npm i" "npm run dev" with node -v = 20+

# Force new environment with: docker compose up --build --force-recreate -d
# Force to revert to the previous commit with: git reset --hard origin/master

# docker compose up --build -d 

services:
  app:
    build:     # 'build' le dice a compose que use el Dockerfile local
      context: .           # Ubicación de tu proyecto
      dockerfile: Dockerfile # nombre del dockerfile
    expose:
      - "3000"
    environment:
      #- NODE_ENV=${NODE_ENV} # Loaded from Dockerfile
      - APP_URL=${SUPABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL} # http://kong:8000
      - SUPABASE_KEY=${SUPABASE_KEY}
      - BROWSERLESS_WS_ENDPOINT=ws://browserless:3000?token=${PUPPETER_KEY}
    depends_on:
      - browserless
    restart: always
    networks:
      - ifc

  browserless:
    image: ghcr.io/browserless/chromium:latest
    environment:
      - TOKEN=${PUPPETER_KEY}
      - TIMEOUT=120000
      - CONCURRENT=5
    shm_size: "1gb"
    restart: always
    networks:
      - ifc

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ifc

volumes:
  caddy_data:
  caddy_config:

networks:
  ifc:
    external: true
